spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: c3ByaW5nLWJvb3QtZGl2aWVuZC1wcm9qZWN0LXR1dG9yaWFsLWp3dC1zZWNyZXQta2V5Cg