spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   

kakao:
  api:
    key: 8d47367161c07dc0cab1a8ab672e6651