spring:
  datasource:
    url: jdbc:mysql://store-mysql:3306/store?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '{cipher}AQAijfMnpxnV7cROWuYAvj6lj9HvZrAEiT/yH9q0azW7cExohdqSEviY5zv0K1pdHH8uPY4PaZBRd8OUPJJDW6XsR4MIPndzSCeqAGzYdVut3DW/T/yLDcoxwwXGNha9INM86l34UWW9fGUpFUHbPYdE7uqjX7R1bmboYIxr3uI38yjRd0H3BLsbXzwsEVyKC3ulFqwWUKhWcnJRg8ayCcRFMCdXVbf2sV1ATL73hsfpFtXrjjtHu9i0xo6vdsmiKMOPrEJSRekEPxNB++4dbDZN9/PbhlzP+GdHb2VeUINMk/27biA8myYcBo00RwACoYgi02oMDYPT5GBeKSZTcN8aXFoH4lDE1kTqd0qsh3TJcgfRZzRXAzR1PT23qosDd2M='


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   
kakao:
  api:
    key: '{cipher}AQA/9IervOu0vDIboI94k2qSlQFU+r9f2Em9jNgmM6Inl3V1yOzARuHCN5o/8/laIyfxAXmW50ukFOhmpV84x8rooDlLXyeYyZQ4N5CZfbVUWPW00LhtxU2L52jmnTju0NWVQCgBnrKd6nDV6/8MVBWLErUd6qa3IId5rx7KWW3ALZDciAix0u9UqKOI3fiQvLEeRrOymUnpLx6YV3B3XSU9Ow0OLcGfSoAF1z0FfaXBlW6jRavf0sxjgsQqIMaIhWDBbhvapCT5R3NS0SCuEfjUeJNTQFAtpcEXn2L0bS1qFgZPb7bd1pXQbraBTVZJILlxgJdrd1zKnA40eFW87/OPMHKREI7b1TOei3+nBW5HOUUkzIrAPj3NcUdJj9Q+yPbuy8rHXSXmMJLu3aD9utb79QEwvo4kUrR5+E/KDxUnqA=='

